version: "1"
client: src/**/java/com/client/**/*.java
configuration: src/**/java/com/configuration/**/*.java
controller: src/**/java/controller/**/*.java
dto: src/**/java/dto/**/*.java
entity: src/**/java/entity/**/*.java
errorhandling: src/**/java/errorhandling/**/*.java
logging: src/**/java/logging/**/*.java
repository: src/**/java/repository/**/*.java
scheduler: src/**/java/scheduler/**/*.java
service: src/**/java/service/**/*.java
utils: src/**/java/utils/**/*.java
resources: src/**/resources/**/*.*