name: Checkmarx scan
on:
  push:
    branches: [ "master","main" ]
  pull_request:
    branches: [ "master","main" ]
    types: [ opened, synchronize, reopened ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: OWASP ZAP API Scan
        uses: zaproxy/action-api-scan@v0.1.1