name: build and sonar
on:
  #push:
    #branches: ["feature-**"]
  pull_request:
    branches: ["main"]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:
  
permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  # maven build
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
  # sonar analysis
  sonar-analysis:
    needs: maven-build
    runs-on: ubuntu-latest
    steps:
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
         path: ~/.sonar/cache
         key: ${{ runner.os }}-sonar
         restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=crypto-prices-tracker
  # docker compose up
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push backend app
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: creationk/crypto-prices-tracker:latest
      - name: Start containers
        run: docker-compose up -d